on: [pull_request]

env:
  BB_SQL_API: ${{ secrets.BB_SQL_API }} # Optional. Users can provide their own SQL Review API URL

jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - uses: actions/checkout@v3
      - name: Check SQL
        # You can change it to a specific version like bytebase/sql-review-action@0.0.4
        # We suggest using the latest version through the tag. Check it at https://github.com/Bytebase/sql-review-action/tags
        uses: bytebase/sql-review-action@main
        with:
          override-file-path: ./sql-review-override.yml
          database-type: POSTGRES
